config/routes.rb
Rails.application.routes.draw do
  get 'room/show'
  post 'room/create'
  get 'room/posts'
  get 'room/search_room'
  get 'room/search'
  
 post 'reserve/confirm'
 post 'reserve/comprete'
 post 'reserve/back' 
 get 'reserve/reserved'
 get 'search' => 'room#search'
 
 get 'room/show'
 
 devise_for :users, controllers: { registrations: 'users/registrations' }
  get '/',to:'room#index'
  get 'reserve/room'
  get 'reserve/comprete'
  get 'reserve/confirm'
  get 'reserve/room'
  
 devise_scope :users do
  post'update_profile',to:'users/registrations#update_profile'
  patch 'update_profile',to:'users/registrations#update_profile'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :reserve
  resources :room
  resources :users
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  validates :start,:end ,presence: true
  validates :people,presence: true
  validate :start_end_check
 
def start_end_check
 errors.add(:end, "は開始時刻より遅い時間を選択してください") if self.start > self.end
 
end
  
end

app/controllers/reserve_controller.rb
class ReserveController < ApplicationController
  def room
   
    @room = Room.find(params[:format])
    @reserve = Reserve.new
    
  end

  
  def confirm
    @room = Room.find(params[:format])
    @reserve = Reserve.new(reserve_params)
      
	if @reserve.invalid?
			render reserve_room_path
			
	else
		@day=((@reserve.end)-(@reserve.start))/86400
		@price=@reserve.people*@day*@room.price
		@reserve.save
	end
   
  end
  
  def comprete
    Reserve.create(reserve_params)
  @reserve = Reserve.new(reserve_params)
  end




  def back
		@reserve = Reserve.new(reserve_params)
		@room = Room.find(params[:format])
		render reserve_room_path
  end
  
  def reserve_params
        params.require(:reserve).permit(:title ,:price,:area,:comment,:roomid,:start,:end,:people)
       
  end
  
  def reserved
    @reserve =Reserve.all
  end
  
end

app/helpers/reserve_helper.rb
module ReserveHelper
end

app/views/reserve/comfirm.html.erb
<div class='confirm'>
 
<div class='confirm-in'>
        <h5>予約内容確認</h5>
        <div class = 'confirm-price'>¥<%= @room.price %>/ 日</div>
        
       <div>
        <p>開始日</p>
        <div class = 'confirm-date'>
        <%= @reserve.start.to_s(:datetime_jp) %></div>
        </div>
        
        <div>
          <p>終了日</p>
          <div class = 'confirm-date'>
         <%= @reserve.end.to_s(:datetime_jp) %></div>
       </div>
       
        <div class = 'confirm-day-people'>使用日数:<%= @day %></div>
       
         <div class = 'confirm-day-people'>人数:<%= @reserve.people %></div>
       
       <div>
          <p>合計金額</p>
        <div class = 'confirm-price'> <%= @price %></div>
        <p>上記内容でよろしければ「予約を確定」を押してください</p>
     </div> 
     
     <div class = 'confirm-form'>
<%= form_for @reserve, method: :post, url: reserve_comprete_path(@reserve) do |f| %>
	<%= f.hidden_field :price,value: @price%>
    	<%= f.hidden_field :title ,value: @room.title%>
    	<%= f.hidden_field :area ,value: @room.area%>   	
    	<%= f.hidden_field :comment,value: @room.comment %>
    	<%= f.hidden_field :roomid,value: @room.id %>
     <%= f.hidden_field :start ,value: @reserve.start%>   	
    	<%= f.hidden_field :end,value: @reserve.end %>
     <%= f.hidden_field :people,value: @reserve.people %>
     
	    <%= f.submit '予約を確定' ,class:'submit'%>
<% end %>
 <%= form_for @reserve, method: :post, url: reserve_back_path(@room) do |f| %>
	<%= f.hidden_field :price,value: @price%>
    	<%= f.hidden_field :title ,value: @room.title%>
    	<%= f.hidden_field :area ,value: @room.area%>   	
    	<%= f.hidden_field :comment,value: @room.comment %>
    	
             <%= f.hidden_field :start ,value: @reserve.start%>   	
    	<%= f.hidden_field :end,value: @reserve.end %>
<%= f.hidden_field :people,value: @reserve.people %>
       
	<%= f.submit 'ルーム詳細に戻る',class:'submit cback' %>
<% end %>
</div>
</div>
</div>

app/views/reserve/comprete.html.erb
<div class = 'comprete'>
  <div class ='comprete-in'>
    <div class = 'comprete-text'>

      <div><p class ='b'>予約した部屋</p>
      <p><%= @reserve.title %></p>
      </div>
      <div><p class ='b'>開始日</p>
        <p><%= @reserve.start %></p>
        </div>
        <div><p class ='b'>終了日</p>
       <p><%= @reserve.end %></p>
       </div>
       <div><p class ='b'>価格</p>
       <p><%= @reserve.price %>円</p>
       </div>
      
       </div>
    </div>
 </div>

app/views/reserve/confirm.html.erb
<div class='confirm'>
 
<div class='confirm-in'>
        <h5>予約内容確認</h5>
        <div class = 'confirm-price'>¥<%= @room.price %>/ 日</div>
        
       <div>
        <p>開始日</p>
        <div class = 'confirm-date'>
        <%= @reserve.start.to_s(:datetime_jp) %></div>
        </div>
        
        <div>
          <p>終了日</p>
          <div class = 'confirm-date'>
         <%= @reserve.end.to_s(:datetime_jp) %></div>
       </div>
       
        <div class = 'confirm-day-people'>使用日数:<%= @day %></div>
       
         <div class = 'confirm-day-people'>人数:<%= @reserve.people %></div>
       
       <div>
          <p>合計金額</p>
        <div class = 'confirm-price'> <%= @price %></div>
        <p>上記内容でよろしければ「予約を確定」を押してください</p>
     </div> 
     
     <div class = 'confirm-form'>
<%= form_for @reserve, method: :post, url: reserve_comprete_path(@reserve) do |f| %>
	<%= f.hidden_field :price,value: @price%>
    	<%= f.hidden_field :title ,value: @room.title%>
    	<%= f.hidden_field :area ,value: @room.area%>   	
    	<%= f.hidden_field :comment,value: @room.comment %>
    	<%= f.hidden_field :roomid,value: @room.id %>
     <%= f.hidden_field :start ,value: @reserve.start%>   	
    	<%= f.hidden_field :end,value: @reserve.end %>
     <%= f.hidden_field :people,value: @reserve.people %>
     
	    <%= f.submit '予約を確定' ,class:'submit'%>
<% end %>
 <%= form_for @reserve, method: :post, url: reserve_back_path(@room) do |f| %>
	<%= f.hidden_field :price,value: @price%>
    	<%= f.hidden_field :title ,value: @room.title%>
    	<%= f.hidden_field :area ,value: @room.area%>   	
    	<%= f.hidden_field :comment,value: @room.comment %>
    	
             <%= f.hidden_field :start ,value: @reserve.start%>   	
    	<%= f.hidden_field :end,value: @reserve.end %>
<%= f.hidden_field :people,value: @reserve.people %>
       
	<%= f.submit 'ルーム詳細に戻る',class:'submit cback' %>
<% end %>
</div>
</div>
</div>

app/views/reserve/home.html.erb
<h1>Reserve#home</h1>
<p>Find me in app/views/reserve/home.html.erb</p>

app/views/reserve/reserved.html.erb
<div class = 'posts'><h5>予約済みルーム一覧</h5>
 <div class='posts-border'>
   
  <div class ='image ppd'>ルーム画像</div>
  <div class = 'title ppd'>ルーム名</div>
  <div class ='room ppd'>ルーム紹介</div>
  <div class ='price ppd'>合計料金</div>
  <div class = 'day ppd'>開始日</div>
  <div class = 'day ppd'>終了日</div>
  <div class = 'day ppd'>予約確定日時</div>
  
 </div>
        
<% @reserve.each do |reserve| %>
          
     <div class='posts-border'>

      <div class = 'posts-image'>
       
       <%id = reserve.roomid%>
       <%room = Room.find(id)%>
       
       <% if room.image.url%>
      
       <%= link_to image_tag(room.image.url ,width: "240px",height: "140px" ),reserve_room_path(room)%>
       <%else%>
       <p>画像がありません</p>
       <%end%>
      </div>
   <%= link_to reserve.title,reserve_room_path(room),class:'title2 ppd2'%>
     
     <div class ='room2 ppd2 '><%= reserve.comment %></div>
     <div class ='price2 ppd2 rr'>¥<%= reserve.price%>	</div>
     <div class ='day3 ppd2 rr'><%= reserve.start.strftime('%Y/%m/%d')%>	</div>
     <div class ='day3 ppd2 rr'><%= reserve.end.strftime('%Y/%m/%d')%>	</div>
     <div class = 'day3 ppd2 rr'><%= reserve.updated_at%>	</div>
     
     </div>
  <% end %>
    
  </table>
  <div class='posts-border'> </div>
</div>

app/views/reserve/room.html.erb
<%= render "shared/error_form" %>
 <div class = 'room'>
  
  <div class = 'room-left'>
   <div class = 'room-image'><%= image_tag @room.image.url%></div>
    <div class= 'stmi'>
     <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg",class:"mx-3 p-1 host-icon nav-trigger roomss"),"/"%>
     <div>
      <div class= 'rooms aa'><%= @room.title %></div>
      <div class= 'rooms aa'><%= @room.area %></div>
     </div>
    </div>
    <div class ='sstt'>
     <div class= 'rooms'><%= @room.comment %></div>
    </div>
  </div>

  <div class = 'room-right'>
   <%= form_for @reserve, method: :post, url: reserve_confirm_path(@room) do |f| %>
   <h3>¥<%= @room.price %>/ 日</h3>
   
   <div class='date'>
    <%= f.label :start ,"開始日" %></br>
    <%= f.date_field :start,class:'date-field', min: Date.current%>
   </div>
   
   <div class='date'>
    <%= f.label :end ,"終了日" %></br>
    <%= f.date_field :end,class:'date-field', min: Date.current%>
   </div>
          
   <div class='date'>
    <%= f.label :people ,"人数" %></br>
    <%= f.number_field :people,class:'date-field'%>
   </div>
      
   <%= f.hidden_field :price,value: @room.price%>
   <%= f.hidden_field :title ,value: @room.title%>
   <%= f.hidden_field :area ,value: @room.area%>   	
   <%= f.hidden_field :comment,value: @room.comment %>
   <%= f.hidden_field :roomid,value: @room.id%>
       
	  <div><%= f.submit "予約する", class:'submit' %>
	  </div>
  </div>
  <%end%>
 
 </div>

app/views/reserve/update.html.erb
<table class = 'room-left'>
      
 <td><%= @share.price %>sss</td>
 </tr><tr>
   
 <td><%= @reserve.start %></td>
 </tr><tr>
   
 <td><%= @reserve.end %></td>
 </tr><tr>
  
 <td><%= @day %></td>
 </tr><tr>
  
 <td><%= @reserve.people %></td>
 </tr>
 
</table>
   
<%= form_with url: 'comprete', model: @reserve do |f| %>　 
<%= f.hidden_field :price,value: @price%>
<%= f.hidden_field :title ,value: @share.title%>
<%= f.hidden_field :area ,value: @share.area%>   	
<%= f.hidden_field :comment,value: @share.comment %>
<%= f.hidden_field :image,value: @share.image%>
<%= f.hidden_field :start ,value: @reserve.area%>   	
<%= f.hidden_field :end,value: @reserve.comment %>
<%= f.submit '送信する' %>

<% end %>