config/routes.rb
Rails.application.routes.draw do
  get 'room/show'
  post 'room/create'
  get 'room/posts'
  get 'room/search_room'
  get 'room/search'
  
 post 'reserve/confirm'
 post 'reserve/comprete'
 post 'reserve/back' 
 get 'reserve/reserved'
 get 'search' => 'room#search'
 
 get 'room/show'
 
 devise_for :users, controllers: { registrations: 'users/registrations' }
  get '/',to:'room#index'
  get 'reserve/room'
  get 'reserve/comprete'
  get 'reserve/confirm'
  get 'reserve/room'
  
 devise_scope :users do
  post'update_profile',to:'users/registrations#update_profile'
  patch 'update_profile',to:'users/registrations#update_profile'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :reserve
  resources :room
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoteShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name=”viewport” content=”width=device-width,initial-scale=1.0″>
  </head>
  <body>
<header>
  <div class="header-inner">
    <div class="header-left-nav">
        
  <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png", alt: "サンプル画像"), '/' %>
 
  <div class='search'>
    <%= search_form_for @q ,url: room_search_room_path do |f| %>
    <%= f.search_field :area_cont , placeholder: "エリア" %>
  <% end %>
  </div>

  <div class='search'><%= search_form_for @q ,url: room_search_room_path do |f| %>
    
    <%= f.search_field :area_or_title_or_comment_cont , placeholder: "キーワード" %>
  <% end %>
  </div>

  </div>
  <div class="header-right-nav">
    <div class='no-user'>
    <% unless user_signed_in?%>
    <li><%= link_to "ログイン",new_user_session_path,class:'link-no sign-in' %></li>
    <li><%= link_to "登録する",new_user_registration_path,class:'link-no sign-up' %></li>
    
   </div>
<%else%>
<div class="nav-item">
  
  <div class ='user-info'>
    <div class='info-label'><%=label(:label1, current_user.name)%></div>
     
    <% unless current_user.image.blank? %>
     <input type="checkbox" id="label1" class="switch" />
  <label for="label1"><%= image_tag current_user.image.url,width: "240px",height: "140px" , class: "icon-image host-icon"%></label>
  <%else%>
  
  
  
 
 <input type="checkbox" id="label1" class="switch" />
   <label for="label1"><img class="mx-3 p-1 host-icon nav-trigger" alt="メニュー" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg" /></label>
   <%end%>
   
   <ul class="header-nav-menu">
     <li><%= link_to "ルーム登録",new_room_path %></li>
     <li><%= link_to "予約済みルーム一覧",reserve_reserved_path,class:'link' %></li>
     <li><%= link_to "登録済みルーム一覧",room_posts_path,class:'link' %></li>
     <li><%= link_to "設定",room_show_path,class:'link' %></li>
     <li><a rel="nofollow" data-method="delete" href="/users/sign_out">ログアウト</a></li>
   </ul>
   
   </div>
 </div>
 <%end%>
</div>
</div>
  
</header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  <footer><p>© 2020 POTEPAN.INC.</p></footer>
  </body>
</html>